# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - overboost

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mikesite.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_59ea23eb2202446ebb2b6b3f9b284f02 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1d12846706ff45d4ac34568fe9df34e4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mikesite.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_59ea23eb2202446ebb2b6b3f9b284f02 }}/overboost:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'overboost'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c3b289f99f0147b4a01c31f0bb931eb8 }}
        images: 'mikesite.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_59ea23eb2202446ebb2b6b3f9b284f02 }}/overboost:${{ github.sha }}'